import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zomato, ZomatoWeb.Endpoint,
cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Zomato.Finch

# Disable Swoosh Local Memory Storage
# config :swoosh, local: false

# As we are using the local mailer, we need to enable the local memory storage
# Before changing the adapter to MailGun, we need to disable the local memory storage
config :swoosh, local: true


# Do not print debug messages in production
config :logger, level: :info

config :zomato, dev_routes: true


config :zomato, Zomato.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_RELAY"),
  username: System.get_env("SMTP_USERNAME"),
  password: System.get_env("SMTP_PASSWORD"),
  ssl: true,
  auth: :always,
  port: 587


# config :phoenix_live_view,
#   # Include HEEx debug annotations as HTML comments in rendered markup
#   debug_heex_annotations: true,
#   # Enable helpful, but potentially expensive runtime checks
#   enable_expensive_runtime_checks: false

config :zomato, Zomaro.Repo,
  url: System.get_env("DATABASE_URL") || "ecto://postgres:postgres@db/zomato"


config :zomato, Zomato.RabbitMQ,
  username: System.get_env("RABBITMQ_USER") || "rabbitmq",
  password: System.get_env("RABBITMQ_PASSWORD") || "rabbitmq",
  host: System.get_env("RABBITMQ_HOST") || "localhost"


## Mailing Service

##Local Mailer
# Currently I am using this as we can see the results in the mailbox

config :zomato, Zomato.Mailer, adapter: Swoosh.Adapters.Local


## MailGun Mailer

# config :zomato, Zomato.Mailer,
#         adapter: Swoosh.Adapters.Mailgun,
#         domain: "sandbox9e41822b1e024ef4b5340210a6edd7ba.mailgun.org",
#         api_key: "e398a17ca79e56adac53c289adbf5403-784975b6-bf9d655e",
#         ssl: [verify: :verify_none]



# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
import_config "dev.secret.exs"
