import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zomato, ZomatoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Zomato.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# config :phoenix_live_view,
#   # Include HEEx debug annotations as HTML comments in rendered markup
#   debug_heex_annotations: true,
#   # Enable helpful, but potentially expensive runtime checks
#   enable_expensive_runtime_checks: false

config :zomato, Zomaro.Repo,
  url: System.get_env("DATABASE_URL") || "ecto://postgres:postgres@db/zomato"


config :zomato, Zomato.RabbitMQ,
  username: System.get_env("RABBITMQ_USER") || "rabbitmq",
  password: System.get_env("RABBITMQ_PASSWORD") || "rabbitmq",
  host: System.get_env("RABBITMQ_HOST") || "localhost"







# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
import_config "dev.secret.exs"
